### ISSUE TITLE
For embedded videos?

### ISSUE THREAD

**Issue by punisher018** [Arcus92/instagram-video-control#4]
What can be done to make the video control bar appear for embedded instagram videos on other sites? In Chrome Extensions, the extension is only authorized to work on instagram.com. 
Your help or improvement of the extension would be gratefully appreciated.

**Comment by Arcus92** [comment]
Hi, thanks for the idea.

I had to add a little bit of trickery to support embedded videos. Turns out, Instagram doesn't want you to use the embedded video at all. Once you played it - or even switched tabs - the video is no longer playable and you need to visit the main Instagram page. I was able to disable this "feature", so you are able to control the embedded video. You can also replay it without opening Instagram.

This implementation may break in the future, should Instagram change their layout or inner-workings.

I'll push v0.5 to the stores and you should be able to test it soon. Please let me know if that works for you.

**Comment by punisher018** [comment]
It works perfectly. Thank you very much. Disabling "the feature" 😄 is also great.
I hope you'll support the extension for a long time, in case instagram changes. Definitely a must have extension.
