### ISSUE TITLE
Can't open linked/shared posts on reels

### ISSUE THREAD

**Issue by back2Lobby** [Arcus92/instagram-video-control#9]
If someone linked a post on their reels, it does convert it to html 5 video player but in return we lose the option to go to the linked post's page. So the "See Post" button doesn't appear on clicking on this video player.

**Comment by Arcus92** [comment]
@back2Lobby Hi, sorry it took me so long to address this issue.
I fixed it. The default Instagram UI is now preserved. I moved it up a bit so you can interact with both UIs.
Let me know if this fixes your issue.

The fix is included in 0.8. This update is currently in review for Firefox and Chrome, but should be released by tomorrow.

**Comment by back2Lobby** [comment]
Thanks, It's all good now. 💖
